
function generatePassword(){
  var numChar = prompt("How many characters do you want in your password?")
  console.log(numChar)

  if (numChar <8){
    alert("The minimum is 8 characters, try again!")
  }
  if(isNaN(numChar) === true){
    alert("please read the instructions")
  }
  console.log(numChar)
}


var bigletters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
var littleletters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
var numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
var specialcharacters = ["!", "#", "$", "%", "&", "(", ")", "*", "+", ",", "-", ".", "/", ":", ";", "<", "=", ">", "?", "@", "[", "]", "^", "_", "`", "{", "|", "}", "~"];

var combos = [bigletters, littleletters, numbers, specialcharacters];


// Assignment Code
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
// YOU HAVE TO CREATE THE FUNCTION, THIS ISN'T AN ACTUAL FUNCTIONING FUNCTION.
// Like, it's structrued like an actual function, however right now when it's firing, there's nothing for it to actually do.
function writePassword() {
  
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;
  //The "password" on the right above is the actual password, generated by the variable in line 8.
  //passwordText is the area on the HTML page where your password is displayed. (I think?)

  copyBtn.removeAttribute("disabled");
  copyBtn.focus();

}

function copyToClipboard() {
  // BONUS 
}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
// generateBtn.addEventListener('click', writePassword)

// BONUS EVENT LISTENER

//create one array for lowercase letters
// create another array for uppercase letters
//create another array for numberes
//create another for special characters
// and create a fifth array in which they're combined and PUSHED into one thing, as they're randomly generated.