function generatePassword(){
  var numChar = prompt("How many characters do you want in your password?")
  console.log(numChar)

var lowerChar = confirm("Do you want lowercase characters?")
var upperChar = confirm("Do you want uppercase characters?")
var specialChar = confirm("Do you want special characters?")
var num = confirm("Do you want numbers?")

  if (numChar <8){
    alert("The minimum is 8 characters, try again!")
  }
  if(isNaN(numChar) === true){
    alert("please read the instructions")
  }
  console.log(numChar)

  if (lowerChar) {
    combos.push(littleletters);
  }
  if (upperChar) {
    combos.push(bigletters)
  }
  if (specialChar) {
    combos.push(specialcharacters)
  }
if (num) {
  combos.push(numbers)
}



while (num>0) {
  var dynamic = Math.floor(Math.random() * combos.length)

  dynamicpassword += combos[dynamic]
}

}

// All the code above is just alerts talking to the user, asking them how many characters they want in their password.
// None of it is code that determines the password that's generated. 
// The only variable from above you need to incorporate into your function is "numChar", because the user will want the password generated to be that number of charaacters.

var bigletters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
var littleletters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
var numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
var specialcharacters = ["!", "#", "$", "%", "&", "(", ")", "*", "+", ",", "-", ".", "/", ":", ";", "<", "=", ">", "?", "@", "[", "]", "^", "_", "`", "{", "|", "}", "~"];

var combos = [];
// Above are your arrays. One array for each type of character, and then an array containing those arrays.

var dynamicpassword;

var generateBtn = document.querySelector("#generate");
// What does the code above actually do???

// Write password to the #password input
// YOU HAVE TO CREATE THE FUNCTION, THIS ISN'T AN ACTUAL FUNCTIONING FUNCTION.
// Like, it's structrued like an actual function, however right now when it's firing, there's nothing for it to actually do.
function writePassword() {
  
  var dynamicpassword = generatePassword();

  console.log (dynamicpassword)

  //above determines the number of characters in the password
  
  var passwordText = document.querySelector("#password");

  passwordText.textContent = dynamicpassword;
  //The "password" on the right above is the actual password, generated by the variable in line 8.
  //passwordText is the area on the HTML page where your password is displayed. (I think?)

  //copyBtn.removeAttribute("disabled");
  //copyBtn.focus();



}

//function copyToClipboard() {
  // BONUS 
//}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
// generateBtn.addEventListener('click', writePassword)

// BONUS EVENT LISTENER

//create one array for lowercase letters
// create another array for uppercase letters
//create another array for numberes
//create another for special characters
// and create a fifth array in which they're combined and PUSHED into one thing, as they're randomly generated.